version: "2"

services:
  mysql:
    image: docker.io/mysql/mysql-server:5.7
    container_name: mysql
    ports:
      - 3306:3306
    environment:
      - MYSQL_ROOT_PASSWORD=${BATS_ROOT_DB_PASSWORD}
      - MYSQL_USER=${BATS_ROOT_DB_USER}
      - MYSQL_PASSWORD=${BATS_ROOT_DB_PASSWORD}
      - MYSQL_DATABASE=${BATS_ROOT_DB_NAME}
      - DEBUG=false
    networks:
      - default
    mem_limit: 512m

  varbase:
    image: ${BATS_VARBASE_DOCKER_IMAGE_NAME}
    container_name: varbase
    ports:
      - 9000:9000
    environment: 
      - PHP_FPM_MAX_CHILDREN=${BATS_PHP_FPM_MAX_CHILDREN}
      - PHP_FPM_REQUEST_MAX_MEMORY_IN_MEGABYTES=${BATS_PHP_FPM_REQUEST_MAX_MEMORY_IN_MEGABYTES}
      - CONTAINER_HEAP_PERCENT=${BATS_CONTAINER_HEAP_PERCENT}
      - DB_DRIVER=${BATS_DB_DRIVER}
      - MYSQL_HOST=${BATS_DB_HOST}
      - MYSQL_PORT=${BATS_DB_PORT}
      - MYSQL_USER=${BATS_DB_USER}
      - MYSQL_PASSWORD=${BATS_DB_PASSWORD}
      - MYSQL_DATABASE=${BATS_DB_NAME}
      - SERVER_NAME=${BATS_SERVER_NAME}
      - HASH_SALT=${BATS_HASH_SALT}
      - TRUSTED_HOST_PATTERNS=${BATS_TRUSTED_HOST_PATTERNS}
    links:
      - ${BATS_STORAGE_SERVICE_NAME}:${BATS_STORAGE_SERVICE_NAME}
    depends_on:
      - ${BATS_STORAGE_SERVICE_NAME}
    command: ["wait-for-it", "${BATS_DB_HOST}:${BATS_DB_PORT}", "--", "/usr/bin/supervisord", "-c", "/etc/supervisord/supervisord.conf"]
    networks:
      - default
    build:
      context: .
      args:
        VERSION_ARG: ${BATS_VARBASE_VERSION}
        RELEASE_ARG: ${BATS_RELEASE_NUMBER}
        BUILD_DATE_ARG: ${BATS_BUILD_DATE}
        VCS_REF_ARG: ${BATS_VCS_REF}
        GITHUB_OAUTH_ARG: ${BATS_GITHUB_OAUTH}
    mem_limit: 512m

networks:
  default:
    external:
      name: docker_default
